/* Shared printing utilities. Browser print dialog can save every bill/report as PDF. */
(function(){
  "use strict";
  function esc(v){return CMSUI.esc(v);}
  function stamp(){return CMSClock.stamp();}
  function openPrint(title, body){
    var w=window.open("","_blank","width=900,height=700");
    if(!w){CMSUI.alert("Please allow pop-ups to print the document.","warning");return;}
    w.document.open();
    w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>'+esc(title)+'</title>'+
      '<style>body{font-family:Arial,sans-serif;color:#222;padding:28px;max-width:900px;margin:auto}h1{margin:0 0 4px;color:#175cdd}h2{margin-top:24px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #ddd;padding:9px;text-align:left}th{background:#f4f8ff}.total{font-size:18px;font-weight:700;text-align:right;margin-top:16px}.muted{color:#666}.footer{margin-top:36px;border-top:1px solid #ddd;padding-top:12px;font-size:12px;color:#666}@media print{button{display:none}body{padding:0}.no-print{display:none}}</style></head><body>'+
      '<div><h1>CMS Hospital Thiruvananthapuram</h1><div class="muted">Clinical &amp; Billing Document</div></div>'+body+
      '<div class="footer">Generated by Clinic Management System<br>Printed on: '+esc(stamp())+'</div>'+
      '<div class="no-print" style="margin-top:20px"><button onclick="window.print()">Print / Save as PDF</button></div>'+
      '<script>window.onload=function(){setTimeout(function(){window.print()},250)}<\/script></body></html>');
    w.document.close();
  }
  function patient(db,id){
    var p=db.patients.find(function(x){return x.patient_id===Number(id);});
    return p||{full_name:"—",patient_id:id,phone_number:"—"};
  }
  function bill(db,type,id){
    var title, bill, items=[], extra="";
    if(type==="registration"){
      bill=db.registration_bills.find(function(x){return x.bill_id===Number(id);}); title="Registration / Consultation Bill";
      if(!bill)return;
      extra='<p><strong>Doctor:</strong> '+esc(CMSUI.doctorName(db,bill.doctor_id))+'</p>'+
        '<p><strong>Registration fee:</strong> '+CMSUI.money(bill.registration_fee)+' &nbsp; <strong>Consultation fee:</strong> '+CMSUI.money(bill.consultation_fee)+'</p>';
      items=[["Registration fee",1,bill.registration_fee,bill.registration_fee],["Consultation fee",1,bill.consultation_fee,bill.consultation_fee]];
    }else if(type==="pharmacy"){
      bill=db.pharmacy_bills.find(function(x){return x.pharmacy_bill_id===Number(id);}); title="Pharmacy Bill";
      if(!bill)return;
      db.pharmacy_bill_items.filter(function(x){return x.pharmacy_bill_id===bill.pharmacy_bill_id;}).forEach(function(i){
        items.push([CMSUI.medicineName(db,i.medicine_id),i.quantity_dispensed,i.unit_selling_price,i.line_amount]);
      });
      extra='<p><strong>Pharmacist:</strong> '+esc(CMSUI.staffName(db,bill.pharmacist_id))+' ('+esc(CMSUI.staffCode(db,bill.pharmacist_id))+')</p>';
    }else if(type==="lab"){
      bill=db.lab_bills.find(function(x){return x.lab_bill_id===Number(id);}); title="Laboratory Bill";
      if(!bill)return;
      db.lab_bill_items.filter(function(x){return x.lab_bill_id===bill.lab_bill_id;}).forEach(function(i){
        items.push([CMSUI.testName(db,db.lab_requests.find(function(r){return r.lab_request_id===i.lab_request_id;}).test_id),i.quantity,i.unit_price,i.line_amount]);
      });
      extra='<p><strong>Laboratory requests:</strong> '+items.length+'</p>';
    }else{return;}
    var p=patient(db,bill.patient_id);
    var rows=items.map(function(x){return "<tr><td>"+esc(x[0])+"</td><td>"+esc(x[1])+"</td><td>"+CMSUI.money(x[2])+"</td><td>"+CMSUI.money(x[3])+"</td></tr>";}).join("");
    var body='<h2>'+esc(title)+'</h2><p><strong>Bill No:</strong> '+esc(type==="registration"?bill.bill_id:type==="pharmacy"?bill.pharmacy_bill_id:bill.lab_bill_id)+
      ' &nbsp; <strong>Date:</strong> '+esc(CMSUI.dateTime(bill.bill_date))+'</p>'+
      '<p><strong>Patient ID:</strong> '+esc(p.patient_id)+' &nbsp; <strong>Patient:</strong> '+esc(p.full_name)+' &nbsp; <strong>Phone:</strong> '+esc(p.phone_number)+'</p>'+
      extra+'<table><thead><tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>'+rows+'</tbody></table>'+
      '<div class="total">Total: '+CMSUI.money(bill.total_amount)+'</div>'+
      '<p><strong>Payment status:</strong> '+esc(bill.payment_status)+' &nbsp; <strong>Method:</strong> '+esc(bill.payment_method||"—")+'</p>';
    openPrint(title,body);
  }
  function consultation(db,id){
    var c=db.consultations.find(function(x){return x.consult_id===Number(id);}); if(!c)return;
    var p=patient(db,c.patient_id), d=CMSUI.doctorName(db,c.doctor_id);
    var pr=db.prescriptions.find(function(x){return x.consultation_id===c.consult_id;});
    var items=pr?db.prescription_items.filter(function(x){return x.prescription_id===pr.prescription_id;}):[];
    var labs=db.lab_requests.filter(function(x){return x.consultation_id===c.consult_id;});
    var medRows=items.map(function(i){return "<tr><td>"+esc(CMSUI.medicineName(db,i.medicine_id,i.dosage_id))+"</td><td>"+esc(i.frequency)+"</td><td>"+esc(i.duration)+"</td><td>"+esc(i.instructions||"—")+"</td></tr>";}).join("");
    var labRows=labs.map(function(l){return "<tr><td>"+esc(CMSUI.testName(db,l.test_id))+"</td><td>"+esc(l.priority)+"</td><td>"+esc(l.status)+"</td></tr>";}).join("");
    var body='<h2>Consultation Record #'+esc(c.consult_id)+'</h2>'+
      '<p><strong>Patient ID:</strong> '+esc(p.patient_id)+' &nbsp; <strong>Patient:</strong> '+esc(p.full_name)+' &nbsp; <strong>Phone:</strong> '+esc(p.phone_number)+'</p>'+
      '<p><strong>Doctor:</strong> '+esc(d)+' &nbsp; <strong>Saved:</strong> '+esc(CMSUI.dateTime(c.created_at))+'</p>'+
      '<h2>Clinical notes</h2><p><strong>Symptoms:</strong> '+esc(c.symptoms)+'</p><p><strong>Diagnosis:</strong> '+esc(c.diagnosis)+'</p><p><strong>Remarks:</strong> '+esc(c.remarks||"—")+'</p>'+
      (items.length?'<h2>Prescription</h2><table><thead><tr><th>Medicine</th><th>Frequency</th><th>Duration</th><th>Instructions</th></tr></thead><tbody>'+medRows+'</tbody></table>':"")+
      (labs.length?'<h2>Lab Requests</h2><table><thead><tr><th>Test</th><th>Priority</th><th>Status</th></tr></thead><tbody>'+labRows+'</tbody></table>':"");
    openPrint("Consultation #"+c.consult_id,body);
  }
  function prescription(db,id){
    var pr=db.prescriptions.find(function(x){return x.prescription_id===Number(id);}); if(!pr)return;
    var c=db.consultations.find(function(x){return x.consult_id===pr.consultation_id;}); if(!c)return;
    var p=patient(db,c.patient_id), d=CMSUI.doctorName(db,c.doctor_id);
    var items=db.prescription_items.filter(function(x){return x.prescription_id===pr.prescription_id;});
    var rows=items.map(function(i){return '<tr><td>'+esc(CMSUI.medicineName(db,i.medicine_id,i.dosage_id))+'</td><td>'+esc(i.frequency)+'</td><td>'+esc(i.duration)+'</td><td>'+esc(i.instructions||"—")+'</td></tr>';}).join("");
    var body='<h2>Medicine Prescription #'+esc(pr.prescription_id)+'</h2>'+      '<p><strong>Patient ID:</strong> '+esc(p.patient_id)+' &nbsp; <strong>Patient:</strong> '+esc(p.full_name)+' &nbsp; <strong>Phone:</strong> '+esc(p.phone_number)+'</p>'+      '<p><strong>Doctor:</strong> '+esc(d)+' &nbsp; <strong>Prescription date:</strong> '+esc(CMSUI.dateTime(pr.created_at))+'</p>'+      '<table><thead><tr><th>Medicine</th><th>Frequency</th><th>Duration</th><th>Instructions</th></tr></thead><tbody>'+rows+'</tbody></table>'+      '<p class="muted" style="margin-top:24px">Please follow the doctor instructions. This prescription is issued by CMS Hospital Thiruvananthapuram.</p>';
    openPrint("Prescription #"+pr.prescription_id,body);
  }

  window.CMSPrint={bill:bill,consultation:consultation,prescription:prescription,open:openPrint};
})();