# Generated by Django 6.1.1 on 2026-09-11 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('exp_year', models.PositiveIntegerField(default=0)),
                ('license_no', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('lab_bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MasterLabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('test_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterMedicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consult_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='cmsapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='cmsapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('lab_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('BILLED', 'Billed'), ('PAID', 'Paid'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='cmsapp.consultation')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='cmsapp.masterlabtest')),
            ],
        ),
        migrations.CreateModel(
            name='LabBillItem',
            fields=[
                ('lab_bill_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lab_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cmsapp.labbill')),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='cmsapp.labrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('dosage_id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dosages', to='cmsapp.mastermedicine')),
            ],
        ),
        migrations.AddField(
            model_name='labbill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_bills', to='cmsapp.patient'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time_slot', models.TimeField()),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='BOOKED', max_length=20)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='cmsapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='cmsapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('pharmacy_bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_bills', to='cmsapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBillItem',
            fields=[
                ('item_bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_bill_items', to='cmsapp.mastermedicine')),
                ('pharmacy_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cmsapp.pharmacybill')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='cmsapp.mastermedicine')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='cmsapp.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('prescription_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('dispensed_status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSED', 'Dispensed')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('dosage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='cmsapp.dosage')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='cmsapp.mastermedicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cmsapp.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationBill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], max_length=20)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_bills', to='cmsapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_bills', to='cmsapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='cmsapp.specialization'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='cmsapp.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='cmsapp.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='pharmacist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_bills', to='cmsapp.staff'),
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='cmsapp.labbill')),
                ('lab_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='cmsapp.labrequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='cmsapp.staff')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='cmsapp.staff'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_number', models.PositiveIntegerField()),
                ('token_date', models.DateField()),
                ('session', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='cmsapp.appointment')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='token', to='cmsapp.registrationbill')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='cmsapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='cmsapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='cmsapp.token'),
        ),
        migrations.CreateModel(
            name='DoctorSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cmsapp.doctor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'session'), name='unique_doctor_session')],
            },
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('doctor', 'token_date', 'session', 'token_number'), name='unique_doctor_token_per_session'),
        ),
    ]
